### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by 1667857557** [BergmannLab/PascalX#29]
>>> from PascalX import genescorer
 = genescorer.chi2sum()
Scorer.load_refpanel('/mnt/g/linux/PascalX/misc/pathtostore/EUR.1KG.GRCh37',parallel=8)

Scorer.load_refpanel("demo/EUR.1KG.GRCh37",keepfile=None)
Scorer.load_genome("./protein_coding_37.txt",ccol=1,cid=0,csymb=5,cstx=2,cetx=3,cs=4,NAgeneid='n/a',header=True)
Scorer.load_GWAS("./SMR_meta_bc.tsv.gz",rscol=0,pcol=3,a1col=2,a2col=1)
>>> Scorer = genescorer.chi2sum()
>>> Scorer.load_refpanel('/mnt/g/linux/PascalX/misc/pathtostore/EUR.1KG.GRCh37',parallel=8)
>>>
>>> Scorer.load_refpanel("demo/EUR.1KG.GRCh37",keepfile=None)
>>> Scorer.load_genome("./protein_coding_37.txt",ccol=1,cid=0,csymb=5,cstx=2,cetx=3,cs=4,NAgeneid='n/a',header=True)
18304 active genes
>>> Scorer.load_GWAS("./SMR_meta_bc.tsv.gz",rscol=0,pcol=3,a1col=2,a2col=1)
R = Scorer.score_chr(chrs=[1])
10355106 SNPs loaded
>>> R = Scorer.score_chr(chrs=[1])
Scoring with method saddle
  0%|                                                                      [ estimated time left: ? ] , AL627309.1     Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/PascalX-0.0.4-py3.10-linux-x86_64.egg/PascalX/genescorer.py", line 667, in score_chr
    res = self.score(G,parallel,unloadRef,method,mode,reqacc,intlimit,nobar,autorescore,keep_idx)
  File "/usr/local/lib/python3.10/dist-packages/PascalX-0.0.4-py3.10-linux-x86_64.egg/PascalX/genescorer.py", line 1080, in score
    R = self._scoremain(G,unloadRef,method,mode,reqacc,intlimit,'',0,nobar,lock,keep_idx)
  File "/usr/local/lib/python3.10/dist-packages/PascalX-0.0.4-py3.10-linux-x86_64.egg/PascalX/genescorer.py", line 984, in _scoremain
    C,R = self._calcGeneSNPcorr_wAlleles(cr,G[i],REF)
  File "/usr/local/lib/python3.10/dist-packages/PascalX-0.0.4-py3.10-linux-x86_64.egg/PascalX/genescorer.py", line 842, in _calcGeneSNPcorr_wAlleles
    if (D[0] in self._GWAS or useAll) and D[1] > self._MAF and (D[0] not in filtered or D[1] < filtered[D[0]][0]) and self._GWAS_alleles[D[0]][0] == D[3] and self._GWAS_alleles[D[0]][1] == D[4]:
IndexError: list index out of range   
This error report appears when we use GWAS data created by ourselves, If we use the common thread to generate the gene score, it will terminate in the process : 
"huang@TNR:/mnt/g/linux/PascalX$ ./pascalx -c [1]  -p 6 protein_coding_37.txt demo/EUR.1KG.GRCh37  out.txt genescoring -sh False -cr 0 -cp 3 SMR_meta_bc.tsv.gz
18305 active genes
10355106 SNPs loaded
Starting genescoring
Scoring with method saddle
  0%|                                                                      [ estimated time left: ? ] , OR4F5
  6%|███▉                                                              [ estimated time left: 01:29 ] , C1orf159        12%|███████▌                                                          [ estimated time left: 01:48 ] , FAM183A        100%|█████████████████████████████████████████████████████████████████ [ estimated time left: 00:00 ] , done
100%|█████████████████████████████████████████████████████████████████ [ estimated time left: 00:00 ] , done
100%|█████████████████████████████████████████████████████████████████ [ estimated time left: 00:00 ] , done
100%|█████████████████████████████████████████████████████████████████ [ estimated time left: 00:00 ] , done
100%|█████████████████████████████████████████████████████████████████ [ estimated time left: 00:00 ] , done
 89%|█████████████████████████████████████████████████████████▋        [ estimated time left: 00:10 ] , GBP1
100%|█████████████████████████████████████████████████████████████████ [ estimated time left: 00:00 ] , done
 95%|█████████████████████████████████████████████████████████████▌    [ estimated time left: 00:03 ] , KCNT2
100%|█████████████████████████████████████████████████████████████████ [ estimated time left: 00:00 ] , done"

**Can you give me some advice on how to deal with it?**

**Comment by Dan-RAI** [comment]
The error is occuring because there is no allele information in the loaded reference panel data. Note that `demo/EUR.1KG.GRCh37` is not a proper reference panel, but only a demo. You have to follow the instructions to download and prepare a proper reference panel. If you want to use allele information, you need to import a `VCF1` based panel. If you do not need allele information, leave a1col=None and a2col=None.

**Comment by 1667857557** [comment]
> The error is occuring because there is no allele information in the loaded reference panel data. Note that `demo/EUR.1KG.GRCh37` is not a proper reference panel, but only a demo. You have to follow the instructions to download and prepare a proper reference panel. If you want to use allele information, you need to import a `VCF` based panel. If you do not need allele information, leave `a1col=None` and `a2col=None`.

Thanks! It worked successfully! By the way, could you provide a sample of the file that is used in the _Pscorer.load_modules()_ function? I'm quite confused about the required file format it needs.

**Comment by Dan-RAI** [comment]
An example can be found in `demo/pw_test.tsv`. First column is name, second column is not used, the remaining columns are the gene symbols included in the module/pathway.
