### ISSUE TITLE
Installation problem with float128.hpp

### ISSUE THREAD

**Issue by roman-tremmel** [BergmannLab/PascalX#31]
Tried to install PascalX using conda but ran into problems:

```
conda create -n pascal python=3.9
conda activate pascal
conda install -c conda-forge python-devtools
conda install -c anaconda setuptools
conda install -c conda-forge boost
conda install -c anaconda libboost

git clone https://github.com/BergmannLab/PascalX.git
cd PascalX
make all
# Create build directories
mkdir -p build
mkdir -p build/include
mkdir -p build/lib
# Copy headers
cp core/*.hpp build/include
# Build core libraries
g++ -fPIC -shared -rdynamic core/ruben.cpp -o build/lib/libruben.so -lquadmath -O2 
core/ruben.cpp:55:10: fatal error: boost/multiprecision/float128.hpp: No such file or directory
 #include <boost/multiprecision/float128.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:16: all] Error 1
```

Of course, it could be that the problem is on my site, but perhaps there is a good known workaround.

**Comment by Dan-RAI** [comment]
Did you verify that the include directories for the boost headers are set ?

**Comment by roman-tremmel** [comment]
OK, I downloaded boost from here: https://www.boost.org/doc/libs/1_62_0/more/getting_started/unix-variants.html, 
installed it locally and added the directory containing the boost folder to the $PATH. Unfortunately, the same error remains.

**Comment by Dan-RAI** [comment]
These are C/C++ header files. You do not have to add the corresponding path to $PATH variable, but to the compiler include path. For examples how to do this, see for instance here: https://stackoverflow.com/questions/973146/how-to-include-header-files-in-gcc-search-path

**Comment by roman-tremmel** [comment]
Perfect. Exported the boost directory as CPATH like `export CPATH=usr/boost/include`. Then I checked whether the directory is recognized using `cpp -v `. And finally, I updated g++ to the same version as cpp. Now it works as expected.

**Comment by roman-tremmel** [comment]
Perfect. Exported the boost directory as CPATH like export CPATH=usr/boost/include. Then I checked whether the directory is recognized using cpp -v . And finally, I updated g++ to the same version as cpp. Now it works as expected.
