### ISSUE TITLE
Does the .load_refpanel load all chromosomes?

### ISSUE THREAD

**Issue by scienception** [BergmannLab/PascalX#38]
I was following the example and got the same error as you:

```
Gscorer.load_refpanel('../demo/EUR.simulated',parallel=1)
Reference panel data not imported. Trying to import...
ERROR:  ../demo/EUR.simulated.chr2.(tped|vcf).gz not found

```
Does this mean you have to have all chromosomes to load to Gscorer? If you don't have all of them do the ones available get loaded or none at all? What should be the format of the file names?

Thank you!

**Comment by Dan-RAI** [comment]
If you do not have all chromosomes in the given path, you have to use the 
`chrlist(list): List of chromosomes to import. (None to import 1-22)` option.

Note also that the reference panel in `demo/` is only a toy to demonstrate the command line interface. 

There are scripts available to import a full 1000G reference panel.

**Comment by scienception** [comment]
Thanks for the clarification. How about chr X and Y? or is it only autosomes?

**Comment by Dan-RAI** [comment]
Not supported at the time being. However, I do not see a fundamental obstruction to extend the code base for that. Feel free to do a pull request in case you add that feature.

**Comment by scienception** [comment]
One last question. Is it possible to provide positions instead of rsid?

**Comment by Dan-RAI** [comment]
Not directly, as position information alone does not uniquely determine the variant. 

However, you could use the function `getSNPatPos` of a matching loaded reference panel to infer which rsids are located at a given position, i.e., to convert pos to rsid.
